### ISSUE TITLE
有木有epoll版本的 给我一份

### ISSUE THREAD

**Issue by tennessine** [kulv2012/mosquitto#1]
qq 389443626
email admin@w3hacker.com

**Comment by kulv2012** [comment]
hi ,不好意思，还有一部分公司代码，得找时间整理一下代码才行哦

## 

世界如此的熙熙攘攘，让年轻的心找不着方向。但，这些人是不能小看的啊！如果，他们开始敲打自己的命令行！

海文 Mob:151-1024-8624 web:http://chenzhenianqing.cn/

在 2014-12-08 14:39:19，"万维网黑客" notifications@github.com 写道：

qq 389443626
email admin@w3hacker.com

**Comment by tennessine** [comment]
不怕 我不会给你发出来的 我只是看看 我已经有个epoll版本的 自己改的 但是继续优化就不会了 能不能给我发一份完整的 我学习下 我不是太擅长c语言
