### ISSUE TITLE
mosquitto 在loop.c里循环db->contexts这个 能不能放到另一个线程

### ISSUE THREAD

**Issue by tennessine** [kulv2012/mosquitto#2]
放到主线程感觉太耗费了 如果100万在线 每次循环一遍

**Comment by kulv2012** [comment]
恩，是的，我测试中100W连接，循环一遍也得秒级别。我目前的做法是可选的只循环一定数目，其实没有解问题。
如果放另外线程应该可以，不过得对contexts加锁了，每次加锁访问，更新完了释放应该是没问题的。
ps: 授权的事情我就放到了后台线程做，授权完了通知主线程继续处理。

**Comment by tennessine** [comment]
你100万连接是怎么测试的 能说说具体测试方法吗

**Comment by tennessine** [comment]
mosquitto 1.4在这方面稍有优化 添加了点儿hash索引

**Comment by kulv2012** [comment]
恩，我的也是加了大量哈希索引，比如订阅树每个节点都是hash。
测试是从多台机器每台发了10W左右连接过去。内外外网各5W
