### ISSUE TITLE
你知道mosquitto给几万人广播消息怎么优化吗 

### ISSUE THREAD

**Issue by tennessine** [kulv2012/mosquitto#7]
我想让他慢点儿推送 以保证其他功能不受影响 现在推送的时候什么都不响应了

**Comment by kulv2012** [comment]
用后端线程做？或者让这些人随机订阅/sub/$randid， rand 100就行，这样量就少很多了。
几万应该卡不了多久吧，顶多几秒，我这epoll，发几万记得没啥压力的

**Comment by tennessine** [comment]
哦 我也改成epoll了 那我就放心了 你那里多少带宽
